[build]
  functions = "netlify/functions"
  publish = "dist" # or "build" or wherever your frontend lives

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functions = "netlify/functions"
  targetPort = 8080 # This tells Netlify Dev your Vite dev server runs on port 8080
  port = 8888       # Optional: This is where Netlify Dev will run (default is 8888)
